eslint:
  enabled: true
  config:
    extensions:
    - .es6
    - .js

ratings:
  paths:
  - "src/**.es6"
  - "src/*/**.es6"
  - "src/**.js"
  - "src/*/**.js"
  - "test/unit/**.js"
  - "test/unit/*/**.js"
  - "test/unit/**.es6"
  - "test/unit/*/**.es6"
